{{- if .Values.contour.enabled -}}
{{- $fullName := include "kso.fullname" . -}}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ $fullName }}
spec:
  ingressClassName: {{ .Values.contour.className }}
  routes:
    - conditions:
        - prefix: /socket
      enableWebsockets: true
      services:
        - name: {{ $fullName }}
          port: 9100
    - conditions:
        - prefix: /
      services:
        - name: {{ $fullName }}
          port: 80
  virtualhost:
    fqdn: {{ .Values.contour.host }}
    {{- if .Values.contour.tls.enabled }}
    tls:
      secretName: {{ .Values.contour.tls.secretName }}
    {{- end }}
{{- end }}
