apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kso.migrationJobName" . }}
  labels:
    {{- include "kso.labels" . | nindent 4 }}
spec:
  {{- include "kso.migrationJobSpec" . | nindent 2 }}
