apiVersion: v1
kind: Service
metadata:
  name: {{ include "kso.fullname" . }}
  labels:
    {{- include "kso.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "kso.selectorLabels" . | nindent 4 }}
