# Default values for kso.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 4spaces/kubernetes-service-orchestrator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

deployment:

  # Valid values: development, production
  # development will show errors, production will not
  environment: ""

  # You need to provide a MySQL database
  database:
    host: ""
    name: ""
    user: ""
    pass: ""

  # The default url is "https://kubernetes.default.svc.cluster.local".
  # But it can be different depending on provider
  kubernetes:
    remoteClusterUrl: "https://kubernetes.default.svc.cluster.local"

  config:
    defaults:
      imagePullSecretName: ""
      certManagerIssuerName: ""

    # Enable email features. Used for "forgot password". This is optional.
#    email:
#      host: ""
#      port: ""
#      user: ""
#      pass: ""
#      sender: ""

  env: [ ]
#  env:
#    - name: ""
#      value: ""

serviceAccount:
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP

ingress:
  enabled: false
  className: ""
  annotations: { }
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

istio:
  enabled: false
  hosts:
    - chart-example.local
  gateway:
    enabled: false
    selector:
      istio: ingressgateway
    tls:
      enabled: false
      secretName: chart-example-tls
  virtualservice:
    enabled: false

contour:
  enabled: false
  className: contour-external
  host: chart-example.local
  tls:
    enabled: false
    secretName: chart-example-tls

resources: { }
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: { }

tolerations: [ ]

affinity: { }
